dependencies:
  override:
     - sudo apt-get update; sudo apt-get install -y zip curl
     - pip install awscli

deployment:
 datalake:
   branch: master
   commands:
     - sudo apt-get update; sudo apt-get install -y zip curl
     - pip install awscli
     - docker build -t jupyter/pyspark-notebook
     - docker save -o docker.image jupyter/pyspark-notebook
     - aws s3 cp docker.image s3://datareply-vkb-docker/
